server:
  port: 8090
  servlet:
    contextPath: /kpc

spring:
  cloud:
    stream:
      bindings:
        in:
          consumer:
            partitioned: true
          destination: producer-consumer-topic
          group: producer-consumer-group
          binder: kafka1
        out:
          producer:
            partitionKeyExpression: payload.payload
            partitionCount: 2
          destination: producer-consumer-topic
          binder: kafka1
        dlq-out-1:
          producer:
            partitionKeyExpression: payload.payload
            partitionCount: 2
          destination: producer-consumer-topic-dlq-1
          binder: kafka2
        dlq-out-2:
          producer:
            partitionKeyExpression: payload.payload
            partitionCount: 2
          destination: producer-consumer-topic-dlq-2
          binder: kafka2
        dlq-in-1:
          consumer:
            partitioned: true
          destination: producer-consumer-topic-dlq-1
          group: producer-consumer-group-dlq
          binder: kafka2
        dlq-in-2:
          consumer:
            partitioned: true
          destination: producer-consumer-topic-dlq-2
          group: producer-consumer-group-dlq
          binder: kafka2
      binders:
        kafka1:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: localhost:9092
            spring.cloud.stream.kafka.binder.zkNodes: localhost:2181
            spring.main.sources: com.sathish.KPC.consumer.DLQConsumer
        kafka2:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.brokers: localhost:9093
            spring.cloud.stream.kafka.binder.zkNodes: localhost:2182
            spring.main.sources: com.sathish.KPC.consumer.DLQConsumer
      kafka:
        binder:
          health-timeout: 60
        bindings:
          in:
            consumer:
              autoCommitOffset: false
          dlq-in-1:
            consumer:
              idleEventInterval: 60000
              autoCommitOffset: true
              enableDlq: true
              dlqName: producer-consumer-topic-error
          dlq-in-2:
            consumer:
              idleEventInterval: 120000
              autoCommitOffset: true
              enableDlq: true
              dlqName: producer-consumer-topic-error

logging:
  level:
    org.springframework.integration: TRACE