server:
  port: 8090
  servlet:
    contextPath: /kpc

spring:
  cloud:
    stream:
      bindings:
        in:
          destination: producer-consumer-topic
          group: producer-consumer-group
        out:
          destination: producer-consumer-topic
        dlq-out-1:
          destination: producer-consumer-topic-dlq-1
        dlq-out-2:
          destination: producer-consumer-topic-dlq-2
        dlq-in-1:
          destination: producer-consumer-topic-dlq-1
          group: producer-consumer-group-dlq
        dlq-in-2:
          destination: producer-consumer-topic-dlq-2
          group: producer-consumer-group-dlq
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          in:
            consumer:
              autoCommitOffset: false
          dlq-in-1:
            consumer:
              idleEventInterval: 30000
              autoCommitOffset: true
              enableDlq: true
              dlqName: producer-consumer-topic-error
          dlq-in-2:
            consumer:
              idleEventInterval: 60000
              autoCommitOffset: true
              enableDlq: true
              dlqName: producer-consumer-topic-error
